In [1]:
#import library yang akan digunakan
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('Customers.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
#untuk menampilkan 5data paling atas pada dataset
dataset.head()

Profession  Age  Annual Income ($)  Work Experience  Family Size  Gender
0            NaN   19              15000                1            4    Male
1       Engineer   21              35000                3            3    Male
2       Engineer   20              86000                1            1  Female
3  Entertainment   31              38000                2            6  Female
4            NaN   22              58000                0            2  Female

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

print(X)

[[nan 19 15000 1 4]
 ['Engineer' 21 35000 3 3]
 ['Engineer' 20 86000 1 1]
 ...
 ['Homemaker' 12 84547 3 3]
 [nan 95 121725 12 3]
 ['Artist' 41 65723 6 7]]


In [4]:
print(y)

['Male' 'Male' 'Female' 'Female' 'Female' 'Female' 'Female' 'Male'
 'Female' 'Male' 'Female' 'Female' 'Female' 'Male' 'Male' 'Female' 'Male'
 'Male' 'Female' 'Male' 'Male' 'Female' 'Male' 'Female' 'Male' 'Female'
 'Male' 'Female' 'Female' 'Male' 'Female' 'Male' 'Male' 'Female' 'Female'
 'Female' 'Female' 'Female' 'Female' 'Female' 'Male' 'Male' 'Female'
 'Female' 'Female' 'Female' 'Female' 'Female' 'Female' 'Female' 'Male'
 'Female' 'Male' 'Female' 'Male' 'Female' 'Male' 'Female' 'Male' 'Male'
 'Male' 'Female' 'Female' 'Male' 'Male' 'Female' 'Female' 'Male' 'Female'
 'Male' 'Female' 'Female' 'Female' 'Male' 'Male' 'Female' 'Male' 'Female'
 'Female' 'Male' 'Male' 'Male' 'Female' 'Female' 'Male' 'Female' 'Female'
 'Female' 'Female' 'Female' 'Male' 'Male' 'Female' 'Female' 'Male'
 'Female' 'Female' 'Male' 'Male' 'Female' 'Female' 'Male' 'Male' 'Male'
 'Female' 'Female' 'Male' 'Male' 'Male' 'Male' 'Female' 'Female' 'Male'
 'Female' 'Female' 'Female' 'Female' 'Female' 'Female' 'Male' 'Femal

In [5]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent') #mengisi kekosongan cell dengan method mostfreq 
imputer.fit(X[:,1:3])
X[:,1: 3] = imputer.transform(X[:,1:3])

In [6]:
print(X)

[[nan 19 15000 1 4]
 ['Engineer' 21 35000 3 3]
 ['Engineer' 20 86000 1 1]
 ...
 ['Homemaker' 12 84547 3 3]
 [nan 95 121725 12 3]
 ['Artist' 41 65723 6 7]]


In [7]:
print(y)

['Male' 'Male' 'Female' 'Female' 'Female' 'Female' 'Female' 'Male'
 'Female' 'Male' 'Female' 'Female' 'Female' 'Male' 'Male' 'Female' 'Male'
 'Male' 'Female' 'Male' 'Male' 'Female' 'Male' 'Female' 'Male' 'Female'
 'Male' 'Female' 'Female' 'Male' 'Female' 'Male' 'Male' 'Female' 'Female'
 'Female' 'Female' 'Female' 'Female' 'Female' 'Male' 'Male' 'Female'
 'Female' 'Female' 'Female' 'Female' 'Female' 'Female' 'Female' 'Male'
 'Female' 'Male' 'Female' 'Male' 'Female' 'Male' 'Female' 'Male' 'Male'
 'Male' 'Female' 'Female' 'Male' 'Male' 'Female' 'Female' 'Male' 'Female'
 'Male' 'Female' 'Female' 'Female' 'Male' 'Male' 'Female' 'Male' 'Female'
 'Female' 'Male' 'Male' 'Male' 'Female' 'Female' 'Male' 'Female' 'Female'
 'Female' 'Female' 'Female' 'Male' 'Male' 'Female' 'Female' 'Male'
 'Female' 'Female' 'Male' 'Male' 'Female' 'Female' 'Male' 'Male' 'Male'
 'Female' 'Female' 'Male' 'Male' 'Male' 'Male' 'Female' 'Female' 'Male'
 'Female' 'Female' 'Female' 'Female' 'Female' 'Female' 'Male' 'Femal

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[0.0 0.0 0.0 ... 15000 1 4]
 [0.0 0.0 1.0 ... 35000 3 3]
 [0.0 0.0 1.0 ... 86000 1 1]
 ...
 [0.0 0.0 0.0 ... 84547 3 3]
 [0.0 0.0 0.0 ... 121725 12 3]
 [1.0 0.0 0.0 ... 65723 6 7]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[1 1 0 0 0 0 0 1 0 1 0 0 0 1 1 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 0 1 1 0 0 0 0
 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 1 0 0 1 1 0 0 1 0 1 0 0 0 1
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0
 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 1 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 1 1 1 0 0
 1 1 1 0 0 0 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 1 0 0 1 0 0 1
 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 1 0 0 0 0 0 1 0 0 0 0 1 1 1 0 1 0 0 0 0 0 1
 0 0 0 0 1 1 1 0 1 0 0 0 0 1 1 1 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 0 1
 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0
 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 0 1 1 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 0 1 1
 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 1 0 0 1 1 0 0 1 0 1
 0 0 0 1 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 0 1 1 1 0 0 1
 1 1 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 1 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 1
 1 1 0 0 1 1 1 0 0 0 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 1 0 0
 1 0 0 1 0 1 0 0 0 0 1 0 

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [13]:
print(X_train)

[[0.0 0.0 0.0 ... 187536 3 6]
 [1.0 0.0 0.0 ... 72594 1 2]
 [0.0 0.0 0.0 ... 62000 9 7]
 ...
 [0.0 0.0 0.0 ... 89000 9 4]
 [0.0 0.0 0.0 ... 91000 8 2]
 [0.0 1.0 0.0 ... 67000 0 2]]


In [14]:
print(X_test)

[[0.0 0.0 0.0 ... 46000 1 2]
 [0.0 0.0 0.0 ... 140000 1 1]
 [1.0 0.0 0.0 ... 151124 15 3]
 ...
 [1.0 0.0 0.0 ... 9000 1 1]
 [1.0 0.0 0.0 ... 95000 1 1]
 [1.0 0.0 0.0 ... 2000 0 1]]


In [15]:
print(y_train)

[1 1 1 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 0 0 1 0 1 1 0 1 0 0 0 0 1 0 1 0
 1 0 1 1 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 1 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 1 0 0 1 0 1 0 0 0
 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 0 1 0 0 1 1
 1 0 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 1 0 1 0
 0 1 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 1 1 1 0 1 1 1 0 1 1 0 1 1 0 1 1 0 0 0
 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 1 0 1 1 0 0 0 1 1 1 0 0
 0 1 0 0 0 1 1 0 1 1 0 1 1 1 0 0 1 0 0 0 0 1 0 1 1 0 0 1 0 1 0 0 0 0 0 1 1
 1 0 1 1 0 1 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 1 0 1 0 0 0 1
 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0
 0 0 0 1 1 0 1 1 0 0 0 1 1 0 0 1 0 1 1 0 0 1 0 1 1 0 1 1 0]


In [16]:
print(y_test)

[0 0 0 1 0 0 1 1 1 0 0 0 1 1 1 1 1 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 0 1
 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 1 0 1 1 1 1 1 0 0 0 0 1 0 1 0
 0 0 0 1 1 0 0 1 0 1 1 1 1 0 0 1 1 1 0 0 1 0 0 0 1 0]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [18]:
print(X_train)

[[0.0 0.0 0.0 ... 2.199541274799711 -0.2503197816421634
  1.6840953276284492]
 [1.0 0.0 0.0 ... -0.15039905503235432 -0.7293490040652962
  -0.6511054915679061]
 [0.0 0.0 0.0 ... -0.3669888816774527 1.1867678856272352
  2.267895532427538]
 ...
 [0.0 0.0 0.0 ... 0.1850146410163038 1.1867678856272352
  0.5164949180302715]
 [0.0 0.0 0.0 ... 0.22590379084547094 0.9472532744156688
  -0.6511054915679061]
 [0.0 1.0 0.0 ... -0.26476600710453485 -0.9688636152768627
  -0.6511054915679061]]


In [19]:
print(X_test)

[[0.0 0.0 0.0 ... -0.6941020803107899 -0.7293490040652962
  -0.6511054915679061]
 [0.0 0.0 0.0 ... 1.227687961660066 -0.7293490040652962
  -1.2349056963669949]
 [1.0 0.0 0.0 ... 1.4551134130098937 2.6238555528966336
  -0.06730528676881732]
 ...
 [1.0 0.0 0.0 ... -1.4505513521503821 -0.7293490040652962
  -1.2349056963669949]
 [1.0 0.0 0.0 ... 0.30768209050380524 -0.7293490040652962
  -1.2349056963669949]
 [1.0 0.0 0.0 ... -1.593663376552467 -0.9688636152768627
  -1.2349056963669949]]
